apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-svc
  template:
    metadata:
      labels:
        app: web-app-svc
    spec:
      containers:
      - name: nodeserver
        image: kumarolipi/jenkins-docker:latest
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: web-app-svc
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
