apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - image: kumarolipi/jenkins-docker
        imagePullPolicy: Always
        name: jenkins-docker


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-dep
  name: my-lbs
spec:
  ports:
  - name: 8080-80
    nodePort: 30213
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-dep
  type: LoadBalancer